estado de reviews
cvirgili438/PF-HenryGadget pull request #150
Opened 2022-12-19 23:32 UTC by stabilini

Agrego en modelo de review la propiedad 'visible' para que el admin pueda ocultar reviews con contenido cuestionable.
Agrego ruta para modificar ese estado (visible es true o false)
Modifico el CRUD de reviews, actions, reducer y constantes para dar funcionamiento al switch que controla la visibilidad de una review desde el panel del admin

2022-12-20 11:32 UTC, ferb0 requested changes
Me parece bien la lógica. Aunque no sé si sea mejor explicitar (cuando se hace una petición al server) de si quiero o no archivar/visible un comentario y no que tome el opuesto del que está actualmente.

2022-12-20 11:32 UTC, ferb0 commented on .gitignore
> +api/src/routes/config/firebase.config.js
Ese archivo es necesario para que funcione la aplicación.

2022-12-20 11:32 UTC, ferb0 commented on api/src/routes/reviews.js
> +    // const {reviewData, idUser} = req.body;
Yo quitaría los comentarios de código copiado..

2022-12-20 11:32 UTC, ferb0 commented on api/src/routes/reviews.js
> +    // const {reviewData, idUser} = req.body;
Eliminaría código copiado.

2022-12-20 11:32 UTC, ferb0 commented on api/src/routes/reviews.js
> +            console.log(element.dataValues.id)
Lo eliminaría, solo es para cuando lo estás probando.

2022-12-21 11:28 UTC, ferb0 reviewed
Todo ok. Solo que se te traspapeló un archivo del Front. Jeje.

2022-12-21 11:28 UTC, ferb0 approved these changes

2022-12-21 11:29 UTC, ferb0 commented
Este. api/src/routes/config/firebase.config.js

2022-12-22 03:07 UTC, Moiso2001 approved these changes
All right

2022-12-22 03:08 UTC, merged